# mysql && create database jumpserver default charset 'utf8'; && grant all on jumpserver.* to 'jumpserver'@'127.0.0.1' identified by 'somepassword';

- name: create database jumperserver
  mysql_db:
    name: jumpserver
  when: jumpserver_remote_db == false

- name: create database jumperserver on remote server
  mysql_db:
    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    login_port: "{{ login_port }}"
    name: jumpserver
  when: db_install_local == true

- name: create user and privilages
  mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_passwd }}"
    priv: "jumpserver.*:ALL,GRANT"
    host: "%"
    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    login_port: "{{ login_port }}"
  when: db_install_local == true

- name: create user and privilages on remote server
  mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_passwd }}"
    priv: "{{ db_name }}.*:ALL,GRANT"
    host: "%"
  when: db_install_local == false

- name: config jumpserver
  template:
    src: config.py.j2
    dest: /opt/jumpserver/config.py
    backup: yes

- name: generate database and datas
  shell: source /opt/py3/bin/activate && cd /opt/jumpserver/utils/ && /bin/bash make_migrations.sh && sleep 3
